# GitHub Sponsors
github: [prof-ramos]

# Patreon
patreon: astrologia-brasil

# Open Collective
open_collective: astrologia-brasil

# Ko-fi
ko_fi: astrologia_br

# Tidelift
tidelift: pypi/astrologia-br

# Community Bridge
community_bridge: astrologia-brasil

# Buy Me a Coffee
buy_me_a_coffee: astrologia_br

# Custom
custom: ["https://astrologia.br/doar", "https://picpay.me/astrologia.br"]