version: '3.8'

services:
  # Main API application
  api:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    container_name: astrology-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/.pytest_cache
    environment:
      - DEBUG=true
      - GEONAMES_USERNAME=${GEONAMES_USERNAME}
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key-change-in-production}
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./dev.db}
    depends_on:
      - redis
      - postgres
    networks:
      - astrology-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: astrology-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./docker/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    networks:
      - astrology-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL database
  postgres:
    image: postgres:15-alpine
    container_name: astrology-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=astrology_dev
      - POSTGRES_USER=astrology_user
      - POSTGRES_PASSWORD=astrology_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - astrology-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U astrology_user -d astrology_dev"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: astrology-pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@astrologia.br
      - PGADMIN_DEFAULT_PASSWORD=admin123
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - astrology-network
    restart: unless-stopped

  # Redis Commander for Redis management
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: astrology-redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    networks:
      - astrology-network
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  astrology-network:
    driver: bridge